server:
  port: 8001

spring:
  application:
    name: provider8001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10 #向注册中心发送心跳的时间间隔  默认为30秒
    lease-expiration-duration-in-seconds: 30  #Eureka服务收到最后一次心跳的等待时间上限  默认为90秒 超时服务则会被剔除
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka