spring:
  application:
    name: consumer
server:
  port: 9002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
