spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://consumer
          predicates:
            - Path=/user

eureka:
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
server:
  port: 80
