spring:
  application:
    name: eureka6002
server:
  port: 6002
eureka:
  instance:
    hostname: eureka6002.com
  client:
    fetch-registry: false  #不从eureka拉取服务
    register-with-eureka: false #不向注册中心注册自己
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka
