spring:
  application:
    name: eureka6001
server:
  port: 6001
eureka:
  instance:
    hostname: eureka6001.com
  client:
    fetch-registry: false  #不从eureka拉取服务
    register-with-eureka: false #不向注册中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
