spring:
  application:
    name: consumer

server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
feign:
  circuitbreaker:
    enabled: true   #openfeign整合hystrix必须添加此配置
