server:
  port: 3344
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luckyalin/spring-cloud-config.git #配置git地址
          search-paths:
            - spring-cloud-config  #配置仓库名称
          force-pull: true
          username:   #git账户名
          password:   #配置密码
  rabbitmq:
    username: admin
    password: 123456
    port: 5672
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"

